/**
 * Standardized Error Codes for API Responses
 */

export const ErrorCodes = {
  // ===== User/Session Errors =====
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_REQUIRED: 'SESSION_REQUIRED',
  SESSION_INVALID: 'SESSION_INVALID',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_MISMATCH: 'SESSION_MISMATCH',
  USER_MISMATCH: 'USER_MISMATCH',
  INVALID_TOKEN: 'INVALID_TOKEN',
  AUTH_SERVICE_UNAVAILABLE: 'AUTH_SERVICE_UNAVAILABLE',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',

  // ===== Authorization Errors =====
  USER_CONTEXT_NOT_FOUND: 'USER_CONTEXT_NOT_FOUND',
  ADMIN_ACCESS_REQUIRED: 'ADMIN_ACCESS_REQUIRED',

  // ===== Resource Errors =====
  TRADER_NOT_FOUND: 'TRADER_NOT_FOUND',
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  MONITOR_NOT_FOUND: 'MONITOR_NOT_FOUND',
  ACTION_NOT_FOUND: 'ACTION_NOT_FOUND',

  // ===== General Validation =====
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  INVALID_PARAMETER_VALUE: 'INVALID_PARAMETER_VALUE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
